In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import random
# data preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split as tts
# data modeling
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense, Activation
# from tensorflow.keras.optimizers import Adam
# from tensorflow.keras import regularizers
# evaluation
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

# hide warnings
import warnings
warnings.filterwarnings('ignore')
from sklearn.decomposition import PCA

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split as tts
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

In [3]:
df = pd.read_csv("Life Expectancy Data_HV22.csv")

In [4]:
df.columns = df.columns.str.strip()

In [5]:
col_null = df.columns[df.isna().any()].tolist()
for i in col_null:
    null = df[i].isna().sum()
    null = str(null)
    print("The column {} has {} null values".format(i, null))

The column Life expectancy has 10 null values
The column Adult Mortality has 10 null values
The column Alcohol has 194 null values
The column Hepatitis B has 553 null values
The column BMI has 34 null values
The column Polio has 19 null values
The column Total expenditure has 226 null values
The column Diphtheria has 19 null values
The column GDP has 448 null values
The column Population has 652 null values
The column thinness  1-19 years has 34 null values
The column thinness 5-9 years has 34 null values
The column Income composition of resources has 167 null values
The column Schooling has 163 null values


In [6]:
for i in col_null:
    df[i].fillna((df[i].mean()), inplace=True)

In [7]:
class MultiColumnLabelEncoder:

    def __init__(self, columns=None):
        self.columns = columns # array of column names to encode


    def fit(self, X, y=None):
        self.encoders = {}
        columns = X.columns if self.columns is None else self.columns
        for col in columns:
            self.encoders[col] = LabelEncoder().fit(X[col])
        return self


    def transform(self, X):
        output = X.copy()
        columns = X.columns if self.columns is None else self.columns
        for col in columns:
            output[col] = self.encoders[col].transform(X[col])
        return output


    def fit_transform(self, X, y=None):
        return self.fit(X,y).transform(X)


    def inverse_transform(self, X):
        output = X.copy()
        columns = X.columns if self.columns is None else self.columns
        for col in columns:
            output[col] = self.encoders[col].inverse_transform(X[col])
        return output

In [8]:
cat_features = [feature for feature in df.columns if df[feature].dtype in ['object', 'bool_']]
multi = MultiColumnLabelEncoder(columns=cat_features)
df = multi.fit_transform(df)

In [9]:
dump(multi, open('encoder.pkl', 'wb'))

NameError: name 'dump' is not defined

In [18]:
df_min_max_scaled = df.copy()

scaler = MinMaxScaler()
scaler.fit(df_min_max_scaled)
# apply normalization techniques
df_min_max_scaled = scaler.transform(df_min_max_scaled)

# view normalized data
print(df_min_max_scaled)

[[0.         1.         1.         ... 0.60350877 0.50527426 0.48792271]
 [0.         0.93333333 1.         ... 0.61052632 0.5021097  0.48309179]
 [0.         0.86666667 1.         ... 0.61754386 0.49578059 0.47826087]
 ...
 [1.         0.13333333 1.         ... 0.04210526 0.45042194 0.48309179]
 [1.         0.06666667 1.         ... 0.05614035 0.45042194 0.47342995]
 [1.         0.         1.         ... 0.38947368 0.45780591 0.47342995]]


In [19]:
df_min_max_scaled = pd.DataFrame(data = df_min_max_scaled, columns = df.columns)

In [20]:
import pickle
#


In [21]:
pickle.dump(scaler, open('scaler.pkl', 'wb'))

In [22]:
X = df_min_max_scaled[['Income composition of resources','Country','Adult Mortality','BMI','HIV/AIDS','Schooling']]
y = df_min_max_scaled['Life expectancy']

X_train, X_test, y_train, y_test = tts(X, y, test_size=0.4, random_state=49)

X_train.head()

model =XGBRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("XGBRegressor")
print("rmse: ",np.sqrt(mse))
print("r2 score: ",r2)


XGBRegressor
rmse:  0.03644841259527988
r2 score:  0.9601590056228894


In [23]:
from pickle import dump

In [25]:
dump(model, open('model.pkl', 'wb'))

In [29]:
list1=['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia (Plurinational State of)', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', "Côte d'Ivoire", 'Cabo Verde',
       'Cambodia', 'Cameroon', 'Canada', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus',
       'Czechia', "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia',
       'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrgyzstan', "Lao People's Democratic Republic",
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania',
       'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius',
       'Mexico', 'Micronesia (Federated States of)', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'Niue', 'Norway', 'Oman', 'Pakistan', 'Palau',
       'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Qatar', 'Republic of Korea',
       'Republic of Moldova', 'Romania', 'Russian Federation', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Swaziland', 'Sweden',
       'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Thailand',
       'The former Yugoslav republic of Macedonia', 'Timor-Leste', 'Togo',
       'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Yemen',
       'Zambia', 'Zimbabwe']

for i in range(0,len(list1)):
    #  <option value="1">Afghanistan</option>
    print('<option value="'+str(i+1)+'">'+list1[i]+'</option>')

<option value="1">Afghanistan</option>
<option value="2">Albania</option>
<option value="3">Algeria</option>
<option value="4">Angola</option>
<option value="5">Antigua and Barbuda</option>
<option value="6">Argentina</option>
<option value="7">Armenia</option>
<option value="8">Australia</option>
<option value="9">Austria</option>
<option value="10">Azerbaijan</option>
<option value="11">Bahamas</option>
<option value="12">Bahrain</option>
<option value="13">Bangladesh</option>
<option value="14">Barbados</option>
<option value="15">Belarus</option>
<option value="16">Belgium</option>
<option value="17">Belize</option>
<option value="18">Benin</option>
<option value="19">Bhutan</option>
<option value="20">Bolivia (Plurinational State of)</option>
<option value="21">Bosnia and Herzegovina</option>
<option value="22">Botswana</option>
<option value="23">Brazil</option>
<option value="24">Brunei Darussalam</option>
<option value="25">Bulgaria</option>
<option value="26">Burkina Faso</opt